config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  


  # config/static_routes.yml
  STATIC_ROUTES.each do |template, locale_paths|
    locale_paths.each do |locale, page|
      get page => "pages##{template}", template: template, locale: locale.to_sym, as: "#{template}_#{locale.to_s.underscore}".to_sym
    end
  end

  resources :contacts, only:[:create], as: 'contacts'
  get 'pages/realtor', as: 'agent_immobilier'
  get 'pages/photo', as: 'photo'
  get 'pages/concept', as: 'concept'
  get 'pages/cv', as: 'cv'
  get 'pages/nl'
  get 'pages/plandusite'
  get 'pages/agenceimmobiliere'
  get 'pages/estimationgratuite'
  get 'pages/formation'

  get "blog", to: 'posts#index', as: :blog
  get "blog/:slug", to: 'posts#show', as: :post

  resources :prices
  resources :partners

  resources :sales do
    resources :link_partners
  end

  namespace :admin do
    resources :lands
  end

  resources :lands, only: [:index, :show, :destroy] do
    collection { post :import }
  end

  resources :estimations, only: [:index, :show, :destroy] do
    collection { post :import }
  end

  resources :clients
  resources :estimations

  get "/sitemap.xml" => "sitemap#index", :format => "xml", :as => :sitemap

  # SEO
  get 'robots', to: 'pages#robots'


end

app/models/action.rb
class Action < ActiveRecord::Base
end

app/models/city.rb
class City < ApplicationRecord
	has_many :neighborhoods, dependent: :destroy
	has_many :lands, dependent: :destroy
	belongs_to :user

	has_many :estimations, dependent: :destroy
	

end

app/models/citysearch.rb
class Citysearch < ApplicationRecord
	has_many :neighborhoods, dependent: :destroy
	has_many :lands, dependent: :destroy
	belongs_to :user

	has_many :estimations, dependent: :destroy
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
	after_create :send_welcome_email
	self.inheritance_column = nil

	private

  def send_welcome_email
    ContactMailer.welcome(self).deliver_now
  end
end

app/models/estimation.rb
class Estimation < ApplicationRecord
	belongs_to :sample
	belongs_to :neighborhood
	belongs_to :city
	belongs_to :citysearch

	extend FriendlyId
  	friendly_id :generate_custom_slug, use: :slugged

	def generate_custom_slug
    	"estimation_immobilier #{address}, #{city.name}"
  	end

  

  	def full_street_address
    	[address, city.name].compact.join(', ')
  	end



    	#Import Lands
  	def self.import(file)
	    CSV.foreach(file.path, headers: true) do |row|
	      Estimation.create! row.to_hash
	    end
  	end
end

app/models/land.rb
class Land < ApplicationRecord

# Validations
	validates :surface, presence: true
 	validates :address, presence: true
	validates :city_id, presence: true
	validates :citysearch, presence: true
	validates :file, presence:true

	belongs_to :neighborhood
	belongs_to :city
	belongs_to :citysearch
	belongs_to :user

	#Geocoding
	geocoded_by :full_street_address
  	after_validation :geocode, if: :address_changed?

  	def full_street_address
    	[address, city.name].compact.join(', ')
  	end

  	#Import Lands
  	def self.import(file)
	    CSV.foreach(file.path, headers: true) do |row|
	      Land.create! row.to_hash
	    end
  	end
end

app/models/link_partner.rb
class LinkPartner < ApplicationRecord
  belongs_to :sale
  belongs_to :partner
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  belongs_to :city
  belongs_to :citysearch
end

app/models/partner.rb
class Partner < ApplicationRecord
	has_many :link_partners, dependent: :destroy
	has_many :sales, through: :link_partners

	has_attachment :photo
end

app/models/price.rb
class Price < ApplicationRecord

	def full_street_address
    	"#{address} #{zip_code}"
  	end

  	extend FriendlyId
  	friendly_id :generate_custom_slug, use: :slugged

  	geocoded_by :full_street_address
  	after_validation :geocode, if: :full_address_changed?

  	def full_address_changed?
    address? || zip_code_changed?
  end

  def generate_custom_slug
    "prix_immobilier #{address} #{zip_code} #{city}"
  end

end

app/models/prospect.rb
class Prospect < ApplicationRecord
end

app/models/sale.rb
class Sale < ApplicationRecord

	geocoded_by :address
  	after_validation :geocode, if: :address_changed?
  	
	has_attachments :photos, maximum: 10

	HEATING = %w(Gaz Electrique Sol Fioul)
	PHASE = ["A VENDRE", "VENDU", "COMPROMIS", "ARCHIVE", "OFFRE EN COURS"]
	SELLER_BUYER = ["Commission Charge ACHETEUR", "Commission Charge VENDEUR"]
	

	extend FriendlyId
  	friendly_id :title, use: :slugged

  	has_many :link_partners, dependent: :destroy
  	has_many :partners, through: :link_partners

end

app/models/sample.rb
class Sample < ApplicationRecord
	has_many :estimations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
        	:recoverable, :rememberable, :trackable, :validatable

    has_many :lands
    has_many :cities
    has_many :citysearches
    

end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
	before_action :authenticate_user!, only: [:index, :show, :new], raise: false
	before_action :set_partner, only: [:show, :destroy, :edit, :update]
	def index
		@partners = Partner.all
		
	end
	def show
		
	end

	def new
		@partner = Partner.new
	end

	def create
		@partner = Partner.new(partner_params)

		if @partner.save
			redirect_to partner_path(@partner)
		else
			render :new
		end
	end

	def destroy
		@partner.destroy
		redirect_to partners_path
	end



	private

	def partner_params
		params.require(:partner).permit(:photo, :name)
	end

	def set_partner
		@partner = Partner.find(params[:id])
	end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/lands_helper.rb
module LandsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/partners/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
		<h1>Partenaires de parutions internets</h1>
			<% if @partners.count >=1 %>
				<table class="table table-striped">
					<thead>
						<tr> 
							<th>Partenaires </th>
							
							<th>Voir<th>
							<th>Modifier</th>
							
						</th>
					</thead>
					<tbody>
						<% @partners.each do |partner| %>
							<tr>
							
								<td><%= partner.name %>
									<%= cl_image_tag partner.photo.path, width: 136, height: 67 %>
								</td>
								<td><%= link_to "voir", partner_path(partner) %></td>
							
								<td>
									<% if current_user.try(:admin?) %>
               							<%= link_to "Effacer", partner_path(partner), method: :delete %>
              						<% end %>
              					</td>

              					<td>
									<% if current_user.try(:admin?) %>
               							<%= link_to "Modifier", edit_partner_path(partner) %>
              						<% end %>
              					</td>
							</tr>

							</p>
						<% end %>
					</tbody>
				</table>
			<% else %>
				<p> Il n' y a pas encore de biens à vendre. </p>
			<% end %>
		</div>
	</div>
	<% if current_user.try(:admin?) %>
		<div class="row">
			<div class="col-md-2 col-md-offset-5">
				<%= link_to "Ajouter une affaire" , new_partner_path, class:"btn btn-danger mb-30"%>
			</div>
		</div>
	<% end %>
</div>

app/views/partners/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<%= simple_form_for @partner do|f| %>
				<%= f.input :name %>
				
				<%= f.input :photo, as: :attachinary %>
				<%= f.button :submit %>
			<% end %>
		</div>
	</div>
</div>

app/views/partners/show.html.erb
<div class="container">
	<div class="row">
		<% if @partner.photo.present? %>
		  	<h2>Voici les annonces avec le partenaire <%= cl_image_tag @partner.photo.path, width: 136, height: 67 %>
			</h2>
		<% else %>
			<h2>Voici les annonces avec le partenaire <%= @partner.name %> </h2>

		<% end %>

		<% @partner.sales.each do |sale| %>
			<p><%= sale.title %></p>
		<% end %>
	</div>
</div>