config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  


  # config/static_routes.yml
  STATIC_ROUTES.each do |template, locale_paths|
    locale_paths.each do |locale, page|
      get page => "pages##{template}", template: template, locale: locale.to_sym, as: "#{template}_#{locale.to_s.underscore}".to_sym
    end
  end

  resources :contacts, only:[:create], as: 'contacts'
  get 'pages/realtor', as: 'agent_immobilier'
  get 'pages/photo', as: 'photo'
  get 'pages/concept', as: 'concept'
  get 'pages/cv', as: 'cv'
  get 'pages/nl'
  get 'pages/plandusite'
  get 'pages/agenceimmobiliere'
  get 'pages/estimationgratuite'
  get 'pages/formation'

  get "blog", to: 'posts#index', as: :blog
  get "blog/:slug", to: 'posts#show', as: :post

  resources :prices
  resources :partners

  resources :sales do
    resources :link_partners
  end

  namespace :admin do
    resources :lands
  end

  resources :lands, only: [:index, :show, :destroy] do
    collection { post :import }
  end

  resources :estimations, only: [:index, :show, :destroy] do
    collection { post :import }
  end

  resources :clients
  resources :estimations

  get "/sitemap.xml" => "sitemap#index", :format => "xml", :as => :sitemap

  # SEO
  get 'robots', to: 'pages#robots'


end

app/models/action.rb
class Action < ActiveRecord::Base
end

app/models/city.rb
class City < ApplicationRecord
	has_many :neighborhoods, dependent: :destroy
	has_many :lands, dependent: :destroy
	belongs_to :user

	has_many :estimations, dependent: :destroy
	

end

app/models/citysearch.rb
class Citysearch < ApplicationRecord
	has_many :neighborhoods, dependent: :destroy
	has_many :lands, dependent: :destroy
	belongs_to :user

	has_many :estimations, dependent: :destroy
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
	after_create :send_welcome_email
	self.inheritance_column = nil

	private

  def send_welcome_email
    ContactMailer.welcome(self).deliver_now
  end
end

app/models/estimation.rb
class Estimation < ApplicationRecord
	belongs_to :sample
	belongs_to :neighborhood
	belongs_to :city
	belongs_to :citysearch

	extend FriendlyId
  	friendly_id :generate_custom_slug, use: :slugged

	def generate_custom_slug
    	"estimation_immobilier #{address}, #{city.name}"
  	end

  

  	def full_street_address
    	[address, city.name].compact.join(', ')
  	end



    	#Import Lands
  	def self.import(file)
	    CSV.foreach(file.path, headers: true) do |row|
	      Estimation.create! row.to_hash
	    end
  	end
end

app/models/land.rb
class Land < ApplicationRecord

# Validations
	validates :surface, presence: true
 	validates :address, presence: true
	validates :city_id, presence: true
	validates :citysearch, presence: true
	validates :file, presence:true

	belongs_to :neighborhood
	belongs_to :city
	belongs_to :citysearch
	belongs_to :user

	#Geocoding
	geocoded_by :full_street_address
  	after_validation :geocode, if: :address_changed?

  	def full_street_address
    	[address, city.name].compact.join(', ')
  	end

  	#Import Lands
  	def self.import(file)
	    CSV.foreach(file.path, headers: true) do |row|
	      Land.create! row.to_hash
	    end
  	end
end

app/models/link_partner.rb
class LinkPartner < ApplicationRecord
  belongs_to :sale
  belongs_to :partner
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  belongs_to :city
  belongs_to :citysearch
end

app/models/partner.rb
class Partner < ApplicationRecord
	has_many :link_partners, dependent: :destroy
	has_many :sales, through: :link_partners

	has_attachment :photo
end

app/models/price.rb
class Price < ApplicationRecord

	def full_street_address
    	"#{address} #{zip_code}"
  	end

  	extend FriendlyId
  	friendly_id :generate_custom_slug, use: :slugged

  	geocoded_by :full_street_address
  	after_validation :geocode, if: :full_address_changed?

  	def full_address_changed?
    address? || zip_code_changed?
  end

  def generate_custom_slug
    "prix_immobilier #{address} #{zip_code} #{city}"
  end

end

app/models/prospect.rb
class Prospect < ApplicationRecord
end

app/models/sale.rb
class Sale < ApplicationRecord

	geocoded_by :address
  	after_validation :geocode, if: :address_changed?
  	
	has_attachments :photos, maximum: 10

	HEATING = %w(Gaz Electrique Sol Fioul)
	PHASE = ["A VENDRE", "VENDU", "COMPROMIS", "ARCHIVE", "OFFRE EN COURS"]
	SELLER_BUYER = ["Commission Charge ACHETEUR", "Commission Charge VENDEUR"]
	

	extend FriendlyId
  	friendly_id :title, use: :slugged

  	has_many :link_partners, dependent: :destroy
  	has_many :partners, through: :link_partners

end

app/models/sample.rb
class Sample < ApplicationRecord
	has_many :estimations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
        	:recoverable, :rememberable, :trackable, :validatable

    has_many :lands
    has_many :cities
    has_many :citysearches
    

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/lands_helper.rb
module LandsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="<%= image_path 'favicon.png' %>" type="image/png" />

    <title><%= content_for?(:meta_title) ? yield(:meta_title).squish : "Alexandre Cordani" %></title>
    <meta name="description" content="<%= (yield(:meta_description) || "").squish %>">
     <meta name="p:domain_verify" content="1dca93071dce474ead1751a7a7c2bbd8"/>

    

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <!-- Google+ Schema.org markup -->
    <meta itemprop="name" content="<%= meta_title %>">
    <meta itemprop="description" content="<%= meta_description %>">
    <meta itemprop="image" content="<%= meta_image %>">

    <%= stylesheet_link_tag    'application', media: 'all' %>

   
    
  </head>
  <body id="<%= "#{controller_path.gsub('/', '_')}_#{action_name}" %>">
    
    <%= render 'shared/navbar' %>

    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    
    <%= javascript_include_tag "application" %>
    <%= cloudinary_js_config %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    


    



  <%= yield(:after_js) %>

  <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-112328714-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-112328714-1');
    </script>

  


  </body>
</html>

<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,700|Raleway:400,100,300,700,500"
  rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">

app/views/pages/agenceimmobiliere.html.erb
<% content_for :meta_title, "Agence Immobilière Saint Maur Des Fossés - Alexandre Cordani- Mandataire Immobilier 3G Immobilier" %>
<% content_for :meta_description, "Votre agence immobilière à Saint-Maur Des Fossés vous permettra de vendre et d'acheter rapidement grace à l'expertise d'Alexandre Cordani, mandataire immobilier au sein du reseau 3G Immobilier." %>

<div class="homepage-banner">
	<div class="homepage-banner-background"></div>
	<div class="homepage-banner-content">
		<div class="container">
    		<h1>Agence Immobilière à Saint-Maur-Des-Fossés</h1>
    		<h2>Alexandre Cordani</h2>
   			<h3>Mandataire immobilier à Saint-Maur-Des-Fossés</h3> 
   			<div class="mt-100"></div> 
   			<h2 style="color:white;"> 06 98 85 38 74 </h2>
   		</div>
	</div>
</div>


<div class="container">
	<div class="row">
		<div class=" col-md-5">
			<div class="mt-50"></div>
			Présentation
			<h1 style="color:#484848; font-size:30px;">AGENCE IMMOBILIERE SAINT-MAUR-DES-FOSSES</h1>
				<p style="color:#8f8e8e;">Je me présente, je m'appelle <b>Alexandre Cordani</b>, je suis <b>mandataire immobilier</b> au sein du reseau <b>3G Immobilier</b></p>
				<p style="color:#8f8e8e;">Je vous propose mes services pour <b>estimer</b>, <b>vendre</b> ou <b>acheter</b> votre appartement ou votre maison sur la commune de <b>Saint-Maur-Des-Fossés</b> et de <b>La Varenne Saint-Hilaire</b>.</p>
		</div>
	</div>
</div>

<div class="container">
	<div class="mt-100">
		<div class="row">
			<div class=" col-md-5">
				Annonces Immobilières
				<h2 style="color:#8f8e8e; font-size:30px;" class="rowHeader">NOTRE SELECTION</h2>
				<p style="color:#8f8e8e;">Nous vous proposons une <b>selection de nos offres immobilères</b> principalement sur la commune de <b>Saint-Maur-Des-Fossés</b> et de <b>La Varenne Saint-Hilaire</b>.</p>
				<p style="color:#8f8e8e;">Si vous ne trouvez pas ce que vous recherchez dans cette selection de 'Agence Immobilière Saint-Maur-Des-Fossés- Alexandre Cordani, merci de m'appeler sur mon portable au <b>06 98 85 38 74</b> afin que je puisse prendre en considération votre demande.</p>
			</div>
		</div>
	</div>
	<div class="row">
		<%= render 'shared/sales' %>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="subtitle "></div>
		</div>
	</div>
</div>
<%= render 'shared/site' %>

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="subtitle "></div>
		</div>
	</div>
</div>

<div class="container mt-100">
	<h3 class="rowHeader"> POURQUOI M'APPELER POUR VENDRE VOTRE BIEN ?</h3>
	<div class="row">
		<div class="col-md-5">
			<h4 style="color:#8f8e8e;">Je vous propose différents <b>services immobiliers</b> qui vont vous permettre de vous <b>démarquer</b> par rapport aux annonces immobilières que vous pouvez voir dans <b>d'autres agences immobilières</b>.</h4>
		</div>
	</div>
	<div class="mb-50"></div>
	<div class="row">
		<div class="col-md-6">
			<h5> <b>1- EVALUATION DE VOTRE BIEN IMMOBILIER</b></h5>
			<p style="color:#8f8e8e;"> Depuis 2001 où j'ai commencé l'immobilier sur la ville de Saint-Maur, j'ai acquis énormémént d'<b>expérience</b> dans <b>l'estimation immobilière</b> sur cette ville.</p>
			<p style="color:#8f8e8e;"> Je vous propose de venir vous voir à domicile afin de vous offrir une estimation de votre bien. Ce service est entièrement <b>GRATUIT</b>.</p>
		</div>
		<div class="col-md-6">
			<%= image_tag(("screen.png"), alt:"Agence Immobilière Saint Maur Des Fossés estime votre bien immobilier", class:"picto img-responsive center-block") %>
		</div>
	</div>
	<div class="mb-50"></div>
	<div class="row">
		<div class="col-md-6">
			<%= image_tag(("photo-camera.png"), alt:"Agence Immobilière Saint Maur Des Fossés photographie votre bien immobilier", class:"picto img-responsive center-block") %>
		</div>
		<div class="col-md-6">
			<h5> <b>2- PHOTOGRAPHIES DE VOTRE BIEN</b></h5>
			<p style="color:#8f8e8e;"> La <b>photographie immobilière</b> est un service très important que je peux apporter à mes clients.</p>
			<p style="color:#8f8e8e;"> Je me suis donc équipé avec un <b>appareil photo haut de gamme</b>.</p>
			<p style="color:#8f8e8e;">Ce service est <b>offert gracieusement</b> à tous mes clients vendeurs que se soit pour un <b>mandat simple que pour un mandat exclusif</b>.</p>
		</div>
	</div>
	<div class="mb-50"></div>
	<div class="row">
		<div class="col-md-6">
			<h5> <b>3- ETABLISSEMENT D'UNE FICHE DESCRIPTIVE</b></h5>
			<p style="color:#8f8e8e;"> <b>La fiche descriptive</b> est très importante car elle permet aux acheteurs de <b>cerner le bien immobilier</b>.</p>
			<p style="color:#8f8e8e;"><b>Rien n'est oublié</b>. Les surfaces des pièces(prises par mes soins), les differentes taxes (charges, taxe foncière) ainsi que l'annonce commerciale qui sera aussi précise que professionnelle afin d'attirer <b>le plus de personnes qualifiées</b>.</p>
		</div>
		<div class="col-md-6">
			<%= image_tag(("browser.png"), alt:"Agence Immobilière Saint Maur Des Fossés etablit une fiche descriptive", class:"picto img-responsive center-block") %>
		</div>
	</div>
	<div class="mb-50"></div>
	<div class="row">
		<div class="col-md-6">
			<%= image_tag(("search.png"), alt:"Agence Immobilière Saint Maur Des Fossés diffuse votre bien sur internet", class:"picto img-responsive center-block") %>
		</div>
		<div class="col-md-6">
			<h5> <b>4- MULTI DIFFUSION IMMOBILIERES</b></h5>
			<p style="color:#8f8e8e;"> Votre <b>annonce immobilière</b> est diffusé sur plus de <b>30 sites immobiliers </b>dont les plus grands (seloger.com, leboncoin.fr, logic-immo.com, ...).</p>
			<%= image_tag(("seloger-logo.png"), class:"mr-20") %>
			<%= image_tag(("leboncoin-logo.png"), class:"mr-20") %>
			<%= image_tag("logicimmo-logo.png") %>
		</div>
	</div>

</div>

<div class="container">
	<div class="row">
		<div class="col-md-5">
		<div class="mt-50"></div>
			Nous situer
		<div class="mt-50"></div>
		<h2 style="color:#484848; font-size:30px;">MANDATAIRE IMMOBILIER SAINT-MAUR-DES-FOSSES</h2>
		<p style="color:#8f8e8e;">Je me deplace à domicile. Mon experience professionnelle (18 ans d'immobilier sur la commune de Saint-Maur-Des-Fossés) me permet d'avoir une expertise professionnelle du métier d'agent immobilier.</p>
		</div>
	</div>
</div>
<%= render 'shared/map-home' %>

app/views/pages/concept.html.erb
<% content_for :meta_title, "Nouveau projet - Opportunité d'affaire" %>
<% content_for :meta_description, "Vous recherchez un projet innovant, une nouvelle facon d'entrprendre, alors cette page est faite pour vous." %>

<div class="image-top-concept">
	<div class="container">
		<div class="row">
			<div class="col-md-12 mt-50">
				<h1>LE MONDE CHANGE</h1>
				<h2> Découvrez une nouvelle opportunité d'affaire</h2>
			</div>
		</div>
	</div>

</div>

app/views/pages/formation.html.erb
<div class="reveal">
			<div class="slides">
				<section>Slide 1</section>
				## Jour 1

---

## Topics
				<section>Slide 2</section>
			</div>
		</div>
		

app/views/pages/plandusite.html.erb
<% content_for :meta_title, "Voici tous les liens du site alexandrecordani.com - agence immobilière saint maur des fossés" %>
<% content_for :meta_description, "Vous trouverez sur cette page tous les liens du site alexandrecordani.com " %>

<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h4>Les rues de Saint-Maur-Des-Fossés</h4>
			<% @prices.each do |price| %>
				<p><%= link_to price.address, price_path(price) %></p>
			<% end %>
		</div>
		<div class="col-md-6">
			<h4>Les parcelles de St Maur</h4>
			<% @estimations.each do |estimation| %>
				<p><%= link_to estimation.full_street_address, estimation_path(estimation) %></p>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<h4>Les annonces de biens à vendre</h4>
			<% @sales.each do |sale| %>
				<p><%= link_to sale.title, sale_path(sale) %></p>
			<% end %>
		</div>
	</div>
	<a href="http://limonads.com" >Répertoire Limonads.com</a>
</div>

app/views/pages/realtor.html.erb
<% content_for :meta_title, "Qui est Alexandre Cordani ?" %>
<% content_for :meta_description, "Vous trouverez sur cette page, une description de Alexandre Cordani, agent immobilier sur Saint Maur Des Fossés." %>


<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1> 
			Je m'appelle <span class="text-shadow"> Alexandre Cordani </span>
			<%=image_tag("photo_identitee_alex.jpg", class:"image_rounded", alt:"Alexandre Cordani")%>
			</h1>
			
			<h2>  Je suis là pour vous <span class="text-shadow">faire gagner du temps </span></h2>
			<h2> Je permets à tous mes clients de trouver exactement <span class="text-shadow">le bien immobilier de leur rêve.</span></h2>
			<h2> <span class="text-shadow">Mon métier : Agent immobilier</span></h2>
			<h2> Ma ville : <span class="text-shadow">Saint-Maur-Des-Fossés</span></h2>
		</div>
		
	</div>

	<div class="row">
		<div class="col-md-2 col-md-offset-5 text-center mt-100 mb-30">
			<button class="hire_me btn btn-primary btn-lg">Contactez-moi</button>
		</div>
	</div>
</div>

<div class='modal'>
      <div class='modal-container'>
        <div>
        	<div>
          		Alexandre Cordani
          	</div>
          	<div>Immobilier 3G</div>
          	<div>06 98 85 38 74</div>
          	<div>alcordani@gmail.com</div>
        	<a class='btn btn-primary mt-30' href='mailto:alcordani@gmail.com'>
    			Contactez moi 
  			</a>
  			<%= link_to "Mon CV", cv_path, class:'btn btn-primary mt-30' %>
    			 
  			</a>
        </div>
     </div>
</div>

app/views/pages/robots.text.erb
<% if Rails.env.production? %>
User-Agent: *
Allow: /
Sitemap: https://www.alexandrecordani.com/sitemap.xml
<% else %>
User-Agent: *
Disallow: /
<% end %>

app/views/shared/_estimations.erb
<div class="row">
		<% if @random.count >= 5 %>	
			<% @random.each do |random| %>
				<div class="col-md-4">
					<p><%= link_to random.full_street_address, estimation_path(random) %></p>
				</div>
			<% end %>
		<% end %>
	</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container-fluid">
	<div class="footer">
		<div class="container">
			<div class="row">
				<div class="col-md-3">
					<h4>Immobilier</h4>
					<p><%= link_to "Prix Immobilier Saint-Maur & La Varenne", prices_path %></p>
					<p><%= link_to "Qui suis-je", agent_immobilier_path %>  -  <%= link_to "Mon CV", cv_path %></p>
					<p><%= link_to "Photo Immobilière", photo_path %></p>
					<p><%= link_to "3G Immobilier", "https://www.3gimmobilier.com/cordani" %></p>
					<p><%= link_to "Agence Immobilière Saint-Maur-Des-Fossés", pages_agenceimmobiliere_path %></p>
					<p><%= link_to "Estimation Gratuite sur St Maur & La Varenne", pages_estimationgratuite_path %></p>
					<p><%= link_to "Blog", blog_path %></p>
					
				</div>
				<div class="col-md-3">
					<h4>Developpeur Web</h4>
					<p><%= link_to "Fleurs d'Antony", "http://www.fleursdantony.com" %>
				</div>
				<div class="col-md-3">
					
				</div>
				<div class="col-md-3">
					<ul class='link-reseauxsociaux'>
						<li><a href="https://www.facebook.com/alcordani3G/" target="_blank"><i class="fa fa-facebook"></i></a></li>
						<li><a href="https://www.instagram.com/immobilier_alexandre_cordani/" target="_blank"><i class="fa fa-instagram"></i></a></li>

					</ul>
					<p class="ml-40"><%= link_to "Plan du site", pages_plandusite_path %></p>
				</div>
			</div>
			<div class="row">
				<div class="text-center">
					<p>- Alexandre Cordani - 06 98 85 38 74</p>
				</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="copyright-footer">
		
		<div>Copyright © 2017 AlexandreCo.</div>
		<%= image_tag(("responsive.jpg"), class:"responsive") %>
		
	</div>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= scope :name, tag: :span, class: "a-class" do %>
    <%= link_to(image_tag("logo.png"), root_path, class:"logo")  %>
  <% end %>
  
  
  

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>
    
    <% if current_user.try(:admin?) %>
      <%= link_to t(".top_call_to_action", default: "Ajout annonces"), new_sale_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>
    <!-- Button (call-to-action) -->
    
  </div>

  <!-- Dropdown list appearing on mobile only -->
 <!--  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div> -->
</div>

app/views/shared/_sales.html.erb
        <div class=""></div>
		<div class="row">
		    <% @sales.each do |sale| %>
				<div class="col-md-4">
					<% if sale.photos.present? %>
						<div class="sale-card" style="background-image: linear-gradient(135deg, rgba(150,109,105,0.2), rgba(150,109,105,0.4)), url('<%= cl_image_path sale.photos.first.path %>');">
					<% else %>
						<%= image_tag(("no-image.png"), class:"sale-card") %>
					<% end %>
						<div class="ribbon">
							<% if sale.phase == "A VENDRE" %>
								<p>A VENDRE</p>
							<% elsif sale.phase == "COMPROMIS" %>
								<p>COMPROMIS</p>
							<% elsif sale.phase == "VENDU" %>
								<p>VENDU</p>
							<% elsif sale.phase == "OFFRE EN COURS" %>
								<p>OFFRE EN COURS</p>
							<% else %>
								<p>A VENDRE</p>
							<% end %>
  							
						</div>
		       			<div class="sale-card-header mt-80">
		       				<h3><%= sale.title %></h3>
		       				<br>
		       				<p><%= sale.city %></p>
		       			</div>
		       		</div>
					<%= link_to "", sale_path(sale), class: "card-link" %>
		        </div>
		    <% end %>
		</div>
		
		<div class="mb-100"></div>

app/views/shared/_sold.html.erb
 <div class=""></div>
		<div class="row">
		    <% @sold.each do |sale| %>
				<div class="col-md-4">
					<div class="sale-card" style="background-image: linear-gradient(135deg, rgba(150,109,105,0.2), rgba(150,109,105,0.4)), url('<%= cl_image_path sale.photos.first.path %>');">
						<div class="ribbon">
							<p>VENDU</p>
  							
						</div>
		       			<div class="sale-card-header mt-80">
		       				<h3><%= sale.title %></h3>
		       				<br>
		       				<p><%= sale.city %></p>
		       			</div>
		       		</div>
					<%= link_to "", sale_path(sale), class: "card-link" %>
		        </div>
		    <% end %>
		</div>
		<div class="mb-100"></div>
		<div class="row">
			<div class="col-md-12 text-center">
				<%= link_to "Voir toutes mes annonces", sales_path, class:"btn-sales" %>
			</div>
		</div>
		<div class="mb-100"></div>
		