config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  


  # config/static_routes.yml
  STATIC_ROUTES.each do |template, locale_paths|
    locale_paths.each do |locale, page|
      get page => "pages##{template}", template: template, locale: locale.to_sym, as: "#{template}_#{locale.to_s.underscore}".to_sym
    end
  end

  resources :contacts, only:[:create], as: 'contacts'
  get 'pages/realtor', as: 'agent_immobilier'
  get 'pages/photo', as: 'photo'
  get 'pages/concept', as: 'concept'
  get 'pages/cv', as: 'cv'
  get 'pages/nl'
  get 'pages/plandusite'
  get 'pages/agenceimmobiliere'
  get 'pages/estimationgratuite'
  get 'pages/formation'

  get "blog", to: 'posts#index', as: :blog
  get "blog/:slug", to: 'posts#show', as: :post

  resources :prices
  resources :partners

  resources :sales do
    resources :link_partners
  end

  namespace :admin do
    resources :lands
  end

  resources :lands, only: [:index, :show, :destroy] do
    collection { post :import }
  end

  resources :estimations, only: [:index, :show, :destroy] do
    collection { post :import }
  end

  resources :clients
  resources :estimations

  get "/sitemap.xml" => "sitemap#index", :format => "xml", :as => :sitemap

  # SEO
  get 'robots', to: 'pages#robots'


end

app/models/action.rb
class Action < ActiveRecord::Base
end

app/models/city.rb
class City < ApplicationRecord
	has_many :neighborhoods, dependent: :destroy
	has_many :lands, dependent: :destroy
	belongs_to :user

	has_many :estimations, dependent: :destroy
	

end

app/models/citysearch.rb
class Citysearch < ApplicationRecord
	has_many :neighborhoods, dependent: :destroy
	has_many :lands, dependent: :destroy
	belongs_to :user

	has_many :estimations, dependent: :destroy
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
	after_create :send_welcome_email
	self.inheritance_column = nil

	private

  def send_welcome_email
    ContactMailer.welcome(self).deliver_now
  end
end

app/models/estimation.rb
class Estimation < ApplicationRecord
	belongs_to :sample
	belongs_to :neighborhood
	belongs_to :city
	belongs_to :citysearch

	extend FriendlyId
  	friendly_id :generate_custom_slug, use: :slugged

	def generate_custom_slug
    	"estimation_immobilier #{address}, #{city.name}"
  	end

  

  	def full_street_address
    	[address, city.name].compact.join(', ')
  	end



    	#Import Lands
  	def self.import(file)
	    CSV.foreach(file.path, headers: true) do |row|
	      Estimation.create! row.to_hash
	    end
  	end
end

app/models/land.rb
class Land < ApplicationRecord

# Validations
	validates :surface, presence: true
 	validates :address, presence: true
	validates :city_id, presence: true
	validates :citysearch, presence: true
	validates :file, presence:true

	belongs_to :neighborhood
	belongs_to :city
	belongs_to :citysearch
	belongs_to :user

	#Geocoding
	geocoded_by :full_street_address
  	after_validation :geocode, if: :address_changed?

  	def full_street_address
    	[address, city.name].compact.join(', ')
  	end

  	#Import Lands
  	def self.import(file)
	    CSV.foreach(file.path, headers: true) do |row|
	      Land.create! row.to_hash
	    end
  	end
end

app/models/link_partner.rb
class LinkPartner < ApplicationRecord
  belongs_to :sale
  belongs_to :partner
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  belongs_to :city
  belongs_to :citysearch
end

app/models/partner.rb
class Partner < ApplicationRecord
	has_many :link_partners, dependent: :destroy
	has_many :sales, through: :link_partners

	has_attachment :photo
end

app/models/price.rb
class Price < ApplicationRecord

	def full_street_address
    	"#{address} #{zip_code}"
  	end

  	extend FriendlyId
  	friendly_id :generate_custom_slug, use: :slugged

  	geocoded_by :full_street_address
  	after_validation :geocode, if: :full_address_changed?

  	def full_address_changed?
    address? || zip_code_changed?
  end

  def generate_custom_slug
    "prix_immobilier #{address} #{zip_code} #{city}"
  end

end

app/models/prospect.rb
class Prospect < ApplicationRecord
end

app/models/sale.rb
class Sale < ApplicationRecord

	geocoded_by :address
  	after_validation :geocode, if: :address_changed?
  	
	has_attachments :photos, maximum: 10

	HEATING = %w(Gaz Electrique Sol Fioul)
	PHASE = ["A VENDRE", "VENDU", "COMPROMIS", "ARCHIVE", "OFFRE EN COURS"]
	SELLER_BUYER = ["Commission Charge ACHETEUR", "Commission Charge VENDEUR"]
	

	extend FriendlyId
  	friendly_id :title, use: :slugged

  	has_many :link_partners, dependent: :destroy
  	has_many :partners, through: :link_partners

end

app/models/sample.rb
class Sample < ApplicationRecord
	has_many :estimations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
        	:recoverable, :rememberable, :trackable, :validatable

    has_many :lands
    has_many :cities
    has_many :citysearches
    

end

app/controllers/prices_controller.rb
class PricesController < ApplicationController

	before_action :set_price, only: [:show, :destroy, :update, :edit]
	before_action :authenticate_user!, only: [ :new ]
	def index
		@prices = Price.all
		
	end

	def new
		@price = Price.new
	end

	def create
		@price = Price.new(price_params)
		if @price.save
			redirect_to price_path(@price)
		else
			render :new
		end
	end

	def show
		
		@average_price_house = Price.average(:price_average_house)
		@average_price_apartment = Price.average(:price_average_apartment)

		@marker = Gmaps4rails.build_markers(@price) do |price, marker|
      		marker.lat price.latitude
      		marker.lng price.longitude
		end

		@contact = Contact.new

		@random = Price.all.shuffle[0..14]

	end

	def destroy
		@price.destroy
			redirect_to prices_path
	end



	def update
		@price.update(price_params)
			redirect_to price_path(@price)
	end

	def edit
	end

	



	private

	def price_params
		params.require(:price).permit(:price_min_house, :price_average_house, :price_max_house, :price_min_apartment, :price_average_apartment, :price_max_apartment, :street, :city, :neighborhood, :type_of_street, :latitude, :longitude, :address, :zip_code)
	end

	def set_price
		@price = Price.friendly.find(params[:id])
	end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/lands_helper.rb
module LandsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/prices/_form.html.erb
 <div class="container">
	
	<%= simple_form_for @price do|f| %>
		<div class="row">
			<div class="col-md-offset-3 col-md-6 mt-30">
				<%= f.input :address %>
				<%= f.input :zip_code %>
				<%= f.input :city %>
				<%= f.select :neighborhood, collection: [["Le Vieux Saint-Maur"], ["Le Parc Saint-Maur"], ["Champignol"], ["La Varenne Saint-Hilaire"], ["Les Mûriers"], ["La Pie"], ["Adamville"], ["Saint-Maur Creteil"]] %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<%= f.input :price_min_apartment %>
				<%= f.input :price_average_apartment %>
				<%= f.input :price_max_apartment %>
				
			</div>
			<div class="col-md-6">
				<%= f.input :price_min_house %>
				<%= f.input :price_average_house %>
				<%= f.input :price_max_house %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-2 col-md-offset-5 mt-30 mb-30">
				<%= f.button :submit %>
			</div>
		</div>
	<% end %>

</div>


<%= content_for(:after_js) do %>
  <script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyAM4X7NgRcGvTeQDuodHhdS5bgt7vGvcBU"></script>
<% end %>

app/views/prices/index.html.erb
<% content_for :meta_title, "Liste des prix des rues de Saint-Maur-Des-Fossés} " %>

<% content_for :meta_description, "Vous trouverez sur cette page toutes les rues de Saint-Maur-Des-Fossés avec leur quartiers}"%>
<div class="container">
	<div class="row">
		<div class="col-md-12">
		<h1 class="mb-50 mt-50">Liste des Rues de Saint-Maur-Des-Fossés</h1>

		

			<% if @prices.count >=1 %>
				<table data-toggle="table" class="table table-striped">
					<thead>
						<tr> 
							<th data-field="street" data-sortable="true">Rues </th>
							<th data-sortable="true">Quartiers</th>
							<th>Voir</th>
							<% if current_user.try(:admin?) %>
								<th>Effacer Modifier</th>
							<% end %>
							
							
						</tr>
					</thead>
					<tbody>
						<% @prices.each do |price| %>
							<tr>
							
								<td><%= price.type_of_street %>
									<%= price.address %></td>
								<td><%= price.neighborhood %></td>
								<td><%= link_to "voir", price_path(price) %></td>
								<% if current_user.try(:admin?) %>
									<td>
								
               							<%= link_to "Effacer", price_path(price), method: :delete %>
               							<%= link_to "Modifier", edit_price_path(price) %>
              						</td>
              					<% end %>
							</tr>
						<% end %>
					</tbody>
				</table>
			<% else %>
				<p> Il n' y a pas encore de rues renseignées. </p>
			<% end %>
		</div>
	</div>
	<% if current_user.try(:admin?) %>
		<div class="row">
			<div class="col-md-2 col-md-offset-5 mt-30">
				<%= link_to "Ajouter une rue" , new_price_path, class:"btn btn-danger mb-30"%>
			</div>
		</div>
	<% end %>
	<div class="mt-50"></div>
</div>

app/views/prices/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-3 col-md-6">
			<%= simple_form_for @price do|f| %>
				<%= f.input :address %>
				<%= f.input :zip_code %>
				<%= f.input :city %>
				<%= f.input :neighborhood, collection: [["Le Vieux Saint-Maur"], ["Le Parc Saint-Maur"], ["Champignol"], ["La Varenne Saint-Hilaire"], ["Les Mûriers"], ["La Pie"], ["Adamville"], ["Saint-Maur Creteil"]] %>
				<%= f.input :price_min_house %>
				<%= f.input :price_average_house %>
				<%= f.input :price_max_house %>
				<%= f.input :price_min_apartment %>
				<%= f.input :price_average_apartment %>
				<%= f.input :price_max_apartment %>
				<%= f.button :submit %>
			<% end %>
		</div>
	</div>
</div>


<%= content_for(:after_js) do %>
  <script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyAM4X7NgRcGvTeQDuodHhdS5bgt7vGvcBU"></script>
<% end %>

app/views/prices/show.html.erb
<% content_for :meta_title, "Prix de vente de votre bien à #{@price.address}, #{@price.city} " %>

<% content_for :meta_description, "Vous trouverez sur cette page tous les prix immobiliers de vente de maisons ou d'appartement à #{@price.address}, #{@price.city}"%>


<div class="container">
	<div class="row">
		<div class="col-md-12 pt-20 text-center">
			<p class="fil_ariane"><%= link_to "Prix Immobilier", prices_path%> >> <%= link_to @price.city, prices_path %></p>
			<div class="price-title pt-20">
				Prix immobilier 
				<%= @price.address %>,
				<%= @price.city %><br>
				<% if @price.neighborhood != nil %>
					<%= @price.neighborhood %>
				<% end %>
			</div>

		</div>
	</div>
	<% if @price.price_min_apartment || @price.price_average_apartment || @price.price_max_apartment || @price.price_min_house || @price.price_average_house || @price.price_max_house != nil %>
		<div class="card">
			<div class="row">
				<div class="col-md-10 col-md-offset-1 col-xs-12 ">
					<div class="col-md-1 col-xs-1">					
					</div>
					<div class="col-md-3 col-xs-1">					
					</div>
					<div class="col-md-2 col-xs-3 text-center">
						Prix m2 bas
					</div>
					<div class="col-md-2 col-xs-3 text-center">
						Prix m2 moyen
					</div>
					<div class="col-md-2 col-xs-3 text-center">
						Prix m2 haut
					</div>
				</div>
			</div>
			<div class="mb-30"></div>
			<% if @price.price_min_apartment && @price.price_average_apartment && @price.price_max_apartment != nil %>
				<div class="row">
					<div class="col-md-10 col-md-offset-1 col-xs-12 ">
						<div class="col-md-1 hidden-xs">
							<i class="fa fa-building fs-40"></i> 
						</div>
						<div class="col-md-3 col-xs-3 pt-8">
							Prix m2 appartement
						</div>
						<div class="col-md-2 col-xs-3 text-center pt-8 price_mini_maxi">
							<%= @price.price_min_apartment %> €
						</div>
						<div class="col-md-2 col-xs-3 text-center pt-8 price_average">
							<%= @price.price_average_apartment %> €
						</div>
						<div class="col-md-2 col-xs-3 text-center pt-8 price_mini_maxi">
							<%= @price.price_max_apartment %> €
						</div>
					
					</div>
				</div>
			<% end %>
			<div class="mb-30"></div>
			<% if @price.price_min_house && @price.price_average_house && @price.price_max_house != nil %>
				<div class="row">
					<div class="col-md-10 col-md-offset-1  col-xs-12  mb-30">
						<div class="col-md-1 hidden-xs">
							<i class="fa fa-home fs-40"></i> 
						</div>
						<div class="col-md-3 col-xs-3 pt-8">
							</i> Prix m2 maison
						</div>
						<div class="col-md-2 col-xs-3 text-center pt-8 price_mini_maxi">
							<%= @price.price_min_house %> €
						</div>
						<div class="col-md-2 col-xs-3 text-center pt-8 price_average">
							<%= @price.price_average_house %> €
						</div>
						<div class="col-md-2 col-xs-3 text-center pt-8 price_mini_maxi">
							<%= @price.price_max_house %> €
						</div>
					</div>
				</div>
			<% end %>
			<div class="row">
				<div class="col-md-2 col-md-offset-5 col-xs-5 col-xs-offset-2">
					<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
					  Estimer mon bien
					</button>
				</div>
			</div>
		
		<!-- Button trigger modal -->
				

			<!-- Modal -->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
				    	<div class="modal-header">
				        	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				        	<h4 class="modal-title" id="myModalLabel">Je souhaite une estimation gratuite de mon bien</h4>
				      	</div>
				      	<div class="modal-body">
				        	<%= simple_form_for @contact do |contact| %>
				        		<%= contact.input :name, label: false, input_html: { class: 'no-border border-bottom', placeholder: 'Votre nom complet ' } %>
				        		<%= contact.input :phone, label: false, input_html: { class: 'no-border border-bottom', placeholder: 'Votre telephone ' }%>
				        		<%= contact.input :mail, label: false, input_html: { class: 'no-border border-bottom', placeholder: 'Votre adresse mail ' } %>
				        		<%= contact.submit 'Me contacter', class:"navbar-wagon-button center " %>
				        	<% end %>
				      	</div>
				      	
				    </div>
				</div>
			</div>
		</div>
	<% end %>
	<div class="row">
		<div class="col-md-12 mt-30">
			<% if @price.price_min_apartment && @price.price_average_apartment && @price.price_max_apartment != nil %>
				<p>Le prix moyen des appartements <%= @price.address %>
						 à 
						<%= @price.city %> est de <%= @price.price_average_apartment %> €, mais le prix moyen de <%= @price.city %> est de <%= @average_price_apartment.round() %> €.</p>
			<% end %>
			<% if @price.price_min_house && @price.price_average_house && @price.price_max_house != nil %>
				<p>Le prix moyen des maisons <%= @price.type_of_street %>
						<%= @price.address %> à 
						<%= @price.city %> est de <%= @price.price_average_house %> €, mais le prix moyen de <%= @price.city %> est de <%= @average_price_house.round() %> €.</p>
			<% end %>
		</div>
	</div>

	<div id="map" class="mb-30 mt-30" style="width: 100%; height: 600px;"></div>

	
	
	<div class="row">
		<div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
			<h2 class="price-title mb-30">D'autres rues de <%= link_to @price.city, prices_path %></h2>
			<% if @random.count >= 5 %>	
				<% @random.each do |random| %>
					<div class="col-md-4">
						<p><%= link_to random.address, price_path(random) %></p>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
		
	</div>

	<div class="mb-50"></div>
	

</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
		

      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {

      var polygons = handler.addPolygons(
    [
      [
        {lat:  48.80910333438192, lng: 2.46093213558197}, { lat: 48.81156919905202, lng: 2.4645504355430603},
        {lat:  48.81133957494126, lng:  2.4653135240077972}, { lat: 48.81108787038087, lng:  2.46546976268291475},
        {lat:  48.810958043324185, lng:  2.4654670804739}, { lat: 48.81080083732257, lng:  2.4653490632772446},
        {lat:  48.810545597315105, lng:  2.4651090055704117}, { lat: 48.81018790584499, lng:  2.4650439620018005},
        {lat:  48.809944, lng:  2.465221}, { lat: 48.809806, lng:  2.465714},
        {lat:  48.8101419, lng:  2.465725}, { lat: 48.810611, lng:  2.466170},
        {lat:  48.810852, lng:  2.4666103}, { lat: 48.810986, lng:  2.4669966},
        {lat:  48.81172, lng:  2.4685308}, { lat: 48.8118482, lng:  2.4687293},
        {lat:  48.81288333, lng:  2.46846109}, { lat: 48.812699, lng:  2.46886879},
        {lat:  48.81241350, lng:  2.469909489}, { lat: 48.81365696, lng:  2.471674382},
        {lat:  48.81434226, lng:  2.47247368}, { lat: 48.815801, lng:  2.4738630},
        {lat:  48.81346973, lng:  2.48015820}, { lat: 48.812579, lng:  2.48599469},
        {lat:  48.811272453, lng:  2.4920350313}, { lat: 48.81041046, lng:  2.4975925683},
        {lat:  48.810523517, lng:  2.503375411}, { lat: 48.8099088, lng:  2.509887814},
        {lat:  48.80965445, lng:  2.510907053}, { lat: 48.80942835, lng:  2.5136107206},
        {lat:  48.80882777, lng:  2.5169044733}, { lat: 48.80718143, lng:  2.519854903},
        {lat:  48.80658082, lng:  2.520273327}, { lat: 48.805619828, lng:  2.5211209058},
        {lat:  48.8045250, lng:  2.5222060}, {lat:  48.8009352, lng:  2.5227639},
        {lat:  48.7995783, lng:  2.5225922}, {lat:  48.7976419, lng:  2.5230857},
        {lat:  48.7969352, lng:  2.5234934}, {lat:  48.7965818, lng:  2.5237295},
        {lat:  48.7943484, lng:  2.5233861}, {lat:  48.7921008, lng:  2.5227639},
        {lat:  48.7905317, lng:  2.5218412}, {lat:  48.7887080, lng:  2.5202962},
        {lat:  48.7869267, lng:  2.5180861}, {lat:  48.7861067, lng:  2.5154039},
        {lat:  48.7850888, lng:  2.5126788}, {lat:  48.7843677, lng:  2.5109407},
        {lat:  48.7841839, lng:  2.5089881}, {lat:  48.7841133, lng:  2.5071427},
        {lat:  48.7844102, lng:  2.5025078}, {lat:  48.7845940, lng:  2.5006625},
        {lat:  48.7845515, lng:  2.4985596}, {lat:  48.7843960, lng:  2.4953624},
        {lat:  48.7840143, lng:  2.4921009}, {lat:  48.7840143, lng:  2.4885818},
        {lat:  48.7844667, lng:  2.4852130}, {lat:  48.7853574, lng:  2.4810931},
        {lat:  48.7865874, lng:  2.4769303}, {lat:  48.7874357, lng:  2.4749991},
        {lat:  48.7891799, lng:  2.4732610}, {lat:  48.7911873, lng:  2.4719307},
        {lat:  48.7943396, lng:  2.4716088}, {lat:  48.7973080, lng:  2.4708792},
        {lat:  48.7997391, lng:  2.4701926}, {lat:  48.8026223, lng:  2.4687978},
        {lat:  48.8045444, lng:  2.4680897}, {lat:  48.8075122, lng:  2.4636909},
        
      ]
    ],
    { strokeColor: '#33cccc'}
  );
        markers = handler.addMarkers(<%= raw @marker.to_json %>);
        handler.bounds.extendWith(markers);
        handler.bounds.extendWith(polygons);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
      $(document).on('ready', function() {

        pos = new google.maps.LatLng( <%= @price.latitude %>, <%= @price.longitude %> );

		var div = document.getElementById('map2');
		var sv = new google.maps.StreetViewPanorama(div);
		sv.setPosition( pos );
		sv.setVisible( true );

		// find the heading by looking from the google car pos to the venue pos
		var service = new google.maps.StreetViewService();
		service.getPanoramaByLocation( pos, 50, function(result, status) {
    	if (status == google.maps.StreetViewStatus.OK)
    		{
        		carPos = result.location.latLng;
        		heading = google.maps.geometry.spherical.computeHeading( carPos, pos );
        		sv.setPov( { heading: heading, pitch: 0, zoom: 1 } );
    	}
    	else {
    			console.log('Street View Not Available');
  		}
		} );
     })
   <% end %>
<% end %>