config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  


  # config/static_routes.yml
  STATIC_ROUTES.each do |template, locale_paths|
    locale_paths.each do |locale, page|
      get page => "pages##{template}", template: template, locale: locale.to_sym, as: "#{template}_#{locale.to_s.underscore}".to_sym
    end
  end

  resources :contacts, only:[:create], as: 'contacts'
  get 'pages/realtor', as: 'agent_immobilier'
  get 'pages/photo', as: 'photo'
  get 'pages/concept', as: 'concept'
  get 'pages/cv', as: 'cv'
  get 'pages/nl'
  get 'pages/plandusite'
  get 'pages/agenceimmobiliere'
  get 'pages/estimationgratuite'
  get 'pages/formation'

  get "blog", to: 'posts#index', as: :blog
  get "blog/:slug", to: 'posts#show', as: :post

  resources :prices
  resources :partners

  resources :sales do
    resources :link_partners
  end

  namespace :admin do
    resources :lands
  end

  resources :lands, only: [:index, :show, :destroy] do
    collection { post :import }
  end

  resources :estimations, only: [:index, :show, :destroy] do
    collection { post :import }
  end

  resources :clients
  resources :estimations

  get "/sitemap.xml" => "sitemap#index", :format => "xml", :as => :sitemap

  # SEO
  get 'robots', to: 'pages#robots'


end

app/models/action.rb
class Action < ActiveRecord::Base
end

app/models/city.rb
class City < ApplicationRecord
	has_many :neighborhoods, dependent: :destroy
	has_many :lands, dependent: :destroy
	belongs_to :user

	has_many :estimations, dependent: :destroy
	

end

app/models/citysearch.rb
class Citysearch < ApplicationRecord
	has_many :neighborhoods, dependent: :destroy
	has_many :lands, dependent: :destroy
	belongs_to :user

	has_many :estimations, dependent: :destroy
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
	after_create :send_welcome_email
	self.inheritance_column = nil

	private

  def send_welcome_email
    ContactMailer.welcome(self).deliver_now
  end
end

app/models/estimation.rb
class Estimation < ApplicationRecord
	belongs_to :sample
	belongs_to :neighborhood
	belongs_to :city
	belongs_to :citysearch

	extend FriendlyId
  	friendly_id :generate_custom_slug, use: :slugged

	def generate_custom_slug
    	"estimation_immobilier #{address}, #{city.name}"
  	end

  

  	def full_street_address
    	[address, city.name].compact.join(', ')
  	end



    	#Import Lands
  	def self.import(file)
	    CSV.foreach(file.path, headers: true) do |row|
	      Estimation.create! row.to_hash
	    end
  	end
end

app/models/land.rb
class Land < ApplicationRecord

# Validations
	validates :surface, presence: true
 	validates :address, presence: true
	validates :city_id, presence: true
	validates :citysearch, presence: true
	validates :file, presence:true

	belongs_to :neighborhood
	belongs_to :city
	belongs_to :citysearch
	belongs_to :user

	#Geocoding
	geocoded_by :full_street_address
  	after_validation :geocode, if: :address_changed?

  	def full_street_address
    	[address, city.name].compact.join(', ')
  	end

  	#Import Lands
  	def self.import(file)
	    CSV.foreach(file.path, headers: true) do |row|
	      Land.create! row.to_hash
	    end
  	end
end

app/models/link_partner.rb
class LinkPartner < ApplicationRecord
  belongs_to :sale
  belongs_to :partner
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  belongs_to :city
  belongs_to :citysearch
end

app/models/partner.rb
class Partner < ApplicationRecord
	has_many :link_partners, dependent: :destroy
	has_many :sales, through: :link_partners

	has_attachment :photo
end

app/models/price.rb
class Price < ApplicationRecord

	def full_street_address
    	"#{address} #{zip_code}"
  	end

  	extend FriendlyId
  	friendly_id :generate_custom_slug, use: :slugged

  	geocoded_by :full_street_address
  	after_validation :geocode, if: :full_address_changed?

  	def full_address_changed?
    address? || zip_code_changed?
  end

  def generate_custom_slug
    "prix_immobilier #{address} #{zip_code} #{city}"
  end

end

app/models/prospect.rb
class Prospect < ApplicationRecord
end

app/models/sale.rb
class Sale < ApplicationRecord

	geocoded_by :address
  	after_validation :geocode, if: :address_changed?
  	
	has_attachments :photos, maximum: 10

	HEATING = %w(Gaz Electrique Sol Fioul)
	PHASE = ["A VENDRE", "VENDU", "COMPROMIS", "ARCHIVE", "OFFRE EN COURS"]
	SELLER_BUYER = ["Commission Charge ACHETEUR", "Commission Charge VENDEUR"]
	

	extend FriendlyId
  	friendly_id :title, use: :slugged

  	has_many :link_partners, dependent: :destroy
  	has_many :partners, through: :link_partners

end

app/models/sample.rb
class Sample < ApplicationRecord
	has_many :estimations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
        	:recoverable, :rememberable, :trackable, :validatable

    has_many :lands
    has_many :cities
    has_many :citysearches
    

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

	before_action :set_sale, only: [:show, :destroy, :edit, :update]

	def index
		@all_sales = Sale.all
		@sales = Sale.where(phase: 'A VENDRE').or(Sale.where(phase: 'COMPROMIS')).or(Sale.where(phase: 'VENDU'))
		@partner = Partner.new
		@link_partner = LinkPartner.new
	end

	def show
		@partner = Partner.new
		@link_partner = LinkPartner.new
    	@markers = Gmaps4rails.build_markers(@sale) do |sale, marker|
      		marker.lat sale.latitude + 0.001
      		marker.lng sale.longitude + 0.001
		end
	end

	def new
		@sale  = Sale.new
	end

	def create
		@sale = Sale.new(sale_params)
			if @sale.save
				redirect_to sale_path(@sale)
			else
				render :new
			end		
	end

	def edit
	end

	def update
		@sale.update(sale_params)
		redirect_to sale_path(@sale)
	end



	def destroy
		@sale.destroy
			redirect_to sales_path
	end


	private

	def sale_params
		params.require(:sale).permit(
			:title,
			:price, 
			:description, 
			:active, 
			:bedroom, 
			:living, 
			:class_energy, 
			:latitude, 
			:longitude, 
			:address, 
			:zip_code, 
			:number_class_energy, 
			:gaz_serre, 
			:number_gaz_serre, 
			:city, 
			:taxe,
  			:exposition,
  			:heating,
  			:phase,
  			:fees,
  			:seller_buyer,
			photos: []
			)
	end

	def set_sale
		@sale = Sale.friendly.find(params[:id])
	end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/lands_helper.rb
module LandsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<%= simple_form_for @sale do|f| %>
				<%= f.input :title %>
				<%= f.input :description %>
				<%= f.input :address %>
				<%= f.input :zip_code %>
				<%= f.input :city %>
				<%= f.input :bedroom %>
				<%= f.input :living %>
				<%= f.input :price %>
				<%= f.input :fees %>
				<%= f.input :seller_buyer, collection: Sale::SELLER_BUYER %>
				<%= f.input :active,     as: :radio_buttons %>
				<%= f.input :phase, collection: Sale::PHASE %>
				<%= f.input :class_energy %>
				<%= f.input :number_class_energy %>
				<%= f.input :gaz_serre %>
				<%= f.input :number_gaz_serre %>
				<%= f.input :heating, collection: Sale::HEATING %>
				<%= f.input :exposition %>
				<%= f.input :taxe %>
				<%= f.input :photos, as: :attachinary %>
				<%= f.button :submit %>
			<% end %>
		</div>
	</div>
</div>

<%= content_for(:after_js) do %>
  <script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyAM4X7NgRcGvTeQDuodHhdS5bgt7vGvcBU"></script>
<% end %>

app/views/sales/edit.html.erb
<%= render 'form' %>

app/views/sales/index.html.erb
<!-- SEO -->
<% content_for :meta_title, "Tous nos biens immobiliers à vendre ou vendus  " %>

<% content_for :meta_description, "Voici tous nos biens immobiliers à Vendre ou Vendus principalement en region parisienne"%>
<%= content_for(:facebook_meta_title) do %>
	<%= "Tous nos biens immobiliers à vendre ou vendus" %>
<% end %>
<%= content_for(:facebook_meta_description) do %>
	<%= "Voici tous nos biens immobiliers à Vendre ou Vendus principalement en region parisienne" %>
<% end %>

<!-- FIN SEO --> 

<% if current_user.try(:admin?) %> 
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1>Annonces Immobilières à Saint-Maur-Des-Fossés</h1>
				<% if @all_sales.count >=1 %>
					<table class="table table-striped">
						<thead>
							<tr> 
								<th>Biens Immobilier </th>
								<th>Phase</th>
								<th>Voir</th>
								<th>
									Modifier
								</th>
								<th>
									Effacer
								</th>

								<th>
									Nbre Partenaires
								</th>
							</tr>
						</thead>
						<tbody>
							<% @all_sales.each do |sale| %>
								<tr>
								
									<td>
										<%= sale.title %> à
										<%= sale.city %>
									</td>
									<td>
										<%= sale.phase %>
									</td>
									<td>
										<%= link_to "voir", sale_path(sale) %>
									</td>
									<td>
	               						<%= link_to "Effacer", sale_path(sale), method: :delete %>
	              					</td>

	              					<td>
	               						<%= link_to "Modifier", edit_sale_path(sale) %>
	              					</td>
	              					<td>
	              						<%= sale.link_partners.count %>
	              					</td>
								</tr>
							<% end %>
						</tbody>
					</table>
				<% else %>
					<p> Il n' y a pas encore de biens à vendre. </p>
				<% end %>
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-2 col-md-offset-5">
			<%= link_to "Ajouter une affaire" , new_sale_path, class:"btn btn-danger mb-30"%>
		</div>
	</div>
<% end %>



<div class="container">
	<h1>Toutes nos annonces de biens immobiliers à vendre</h1>
	<div class="row">
		<% @sales.each do |sales| %>
			<div class="col-md-4">
				<div class="sale-card" style="background-image: linear-gradient(135deg, rgba(150,109,105,0.2), rgba(150,109,105,0.4)), url('<%= cl_image_path sales.photos.first.path %>'); margin-bottom:30px;">
					<div class="ribbon">
						<% if sales.phase == "VENDU" %>
							<p>VENDU</p>
						<% elsif  sales.phase == "COMPROMIS" %>
							<p>COMPROMIS</p>
						<% else %>
							<p><%= sales.price %> €</p>
						<% end %>
  							
						</div>
					<div class="sale-card-header mt-80">
		       			<h3><%= sales.title %></h3>
		       			<br>
		       			<p><%= sales.city %></p>
		       		</div>	
					<%= link_to "", sale_path(sales), class: "card-link" %>
				</div>
			</div>
		<% end %>
	</div>
</div>

	
		<div 

app/views/sales/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<%= simple_form_for @sale do|f| %>
				<%= f.input :title %>
				<%= f.input :description %>
				<%= f.input :address %>
				<%= f.input :zip_code %>
				<%= f.input :city %>
				<%= f.input :bedroom %>
				<%= f.input :living %>
				<%= f.input :price %>
				<%= f.input :active,     as: :radio_buttons %>
				<%= f.input :class_energy %>
				<%= f.input :photos, as: :attachinary %>
				<%= f.button :submit %>
			<% end %>
		</div>
	</div>
</div>

<%= content_for(:after_js) do %>
  <script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyAM4X7NgRcGvTeQDuodHhdS5bgt7vGvcBU"></script>
<% end %>

app/views/sales/shared/_conseiller.html.erb
<%= prop :RealEstateAgent do %>
	<div class="col-md-4">
		<%= prop :image, image_tag("photo_identitee_alex.jpg", class:"image_rounded-show", alt:"Alexandre Cordani")%>
	</div>
	<div class="col-md-8">
		<div class="carte-nego">
			<% YAML.load(File.open("#{Rails.root}/db/data/realtor.yml")).each do |realtor| %>
				
				<h3> <%= realtor['firstname'] %> <%= prop :name, realtor['lastname'] %></h3>
				<p><%= realtor['title'] %></p>
				<p><%= prop :telephone,realtor['phone-number'] %></p>
				<p><%= prop :address, realtor['address'] %></p>
				<p><%= prop :email, realtor['mail'] %></p>

			<% end %>
			
		</div>
	</div>
<% end %>

app/views/sales/shared/_conso_energetique.html.erb
    <div class="conso_energetique">
      <% if @sale.class_energy == "A" %>
        <p class="energy color-a"> 50 - A </p>
      <% elsif @sale.class_energy == "B" %>
        <p class="energy color-b"> DE 51 A 90 - B </p>
      <% elsif @sale.class_energy == "C" %>
        <p class="energy color-c"> DE 91 A 150 - C </p>
      <% elsif @sale.class_energy == "D" %>
        <p class="energy color-d"> DE 151 A 230 - D </p>
      <% elsif @sale.class_energy == "E" %>
        <p class="energy color-e"> DE 231 A 330 - E </p>
      <% elsif @sale.class_energy == "F" %>
        <p class="energy color-f"> DE 331 A 450 - F </p>
      <% elsif @sale.class_energy == "G" %>
        <p class="energy color-g"> > 450 - G </p>
      <% else  %>
        <p style="margin-bottom:0;">  DPE VIERGE </p>       
      <% end %>
      <p class="number_class_energy"><%= @sale.number_class_energy %>(KWh/m²/an)</p>
	</div>

app/views/sales/shared/_dpe.html.erb
<!-- Affichage ecran computer -->
<div class="row">
  <div class="col-md-4 hidden-xs col-sm-6">
    <h4>CONSOMMATION ENERGETIQUE</h4>
  </div>
  <div class="col-md-4 hidden-xs col-sm-6">
    <h4>EMISSION DE GAZ EFFET DE SERRE</h4>
  </div>  
</div>

<div class="row">
  <div class="col-md-4 hidden-xs col-sm-6">
    <%= render 'sales/shared/conso_energetique' %>  
  </div>

  <div class="col-md-4 hidden-xs col-sm-6">
    <%= render 'sales/shared/gaz_serre' %>
  </div>
</div>
<!-- FIN Affichage ecran computer -->

<!-- Affichage ecran smartphone -->
<div class="row">
  <div class="col-xs-12 hidden-lg hidden-md hidden-sm">
    <p class="title-conso-energy">CONSOMMATION ENERGETIQUE</p>
    <%= render 'sales/shared/conso_energetique' %>
    <div class="mb-20"></div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 hidden-lg hidden-md hidden-sm">
    <p class="title-conso-energy">EMISSION DE GAZ EFFET DE SERRE</p>
    <%= render 'sales/shared/gaz_serre' %>
  </div>
</div>

app/views/sales/shared/_gaz_serre.html.erb
<div class="conso_energetique">
        <% if @sale.gaz_serre == "A" %>
          <p class="energy color-a2"> <= 5 - A </p>
        <% elsif @sale.gaz_serre == "B" %>
          <p class="energy color-b2"> DE 6 A 10 - B </p>
        <% elsif @sale.gaz_serre == "C" %>
          <p class="energy color-c2"> DE 11 A 20 - C </p>
        <% elsif @sale.gaz_serre == "D" %>
          <p class="energy color-d2"> DE 21 A 35 - D </p>
        <% elsif @sale.gaz_serre == "E" %>
          <p class="energy color-e2"> DE 36 A 55 - E </p>
        <% elsif @sale.gaz_serre == "F" %>
          <p class="energy color-f2"> DE 56 A 80 - F </p>
        <% elsif @sale.gaz_serre == "G" %>
          <p class="energy color-g2"> > 80 - G </p>
        <% else  %>
          <p style="margin-bottom:0;">  DPE VIERGE </p>       
        <% end %>
        <p class="number_class_energy"><%= @sale.number_gaz_serre %>(KgCO2/m²/an)</p>
</div>

app/views/sales/shared/_partenaires.html.erb
<h4>Retrouvez l'annnonce sur nos sites partenaires</h4>

<%= @sale.partners.name %>

app/views/sales/shared/_photo_conseiller.html.erb
<%= prop :image, image_tag("photo_identitee_alex.jpg", class:"image_rounded-show", alt:"Alexandre Cordani")%>

app/views/sales/show.html.erb
<!-- SEO -->
<% content_for :meta_title, "A vendre sur #{@sale.city}, #{@sale.description.truncate(60)}  " %>

<% content_for :meta_description, "Nouveau bien à vendre sur #{@sale.city}, #{@sale.bedroom} chambres, #{@sale.description.truncate(150)}"%>
<% content_for :meta_image, cl_image_path(@sale.photos.first.path)%>
<%= content_for(:facebook_meta_title) do %>
	<%= "A vendre sur #{@sale.city}, #{@sale.description}" %>
<% end %>
<%= content_for(:facebook_meta_description) do %>
	<%= "Nouveau bien à vendre sur #{@sale.city}, #{@sale.bedroom} chambres, #{@sale.description}" %>
<% end %>

<!-- FIN SEO -->

<div class="container">
	<div class="mt-20"></div>
	<div class="row">
		<div class="col-md-10 hidden-xs">
			<h1 class="title"><%= @sale.title %></h1>
			<h3><%= @sale.city %></h3>
		</div>
		<div class="hidden-md hidden-sm hidden-lg col-xs-12">
			<h3 style="color:#006666; font-size:18px!important;"><%=@sale.city %></h3>
		</div>
		<div class="col-md-2 hidden-xs hidden-md hidden-sm">
			<div class="label-sale text-center">
				<% if @sale.phase == "A VENDRE" %>
					A VENDRE
				<% elsif @sale.phase == "COMPROMIS" %>
					COMPROMIS
				<% elsif @sale.phase == "VENDU" %>
					VENDU
				<% elsif @sale.phase == "ARCHIVE" %>
					VENDU
				<% elsif @sale.phase == "OFFRE EN COURS" %>
					OFFRE EN COURS
				<% else %>
					A VENDRE
				<% end %>
			</div>	
		</div>
	</div>
	<div class="mb-30"></div>
	<div class="row">
		<div class="col-md-2 hidden-xs hidden-md hidden-sm">
			<p><%= pluralize(@sale.bedroom, "Chambre")%></p>
		</div>
		<div class="hidden-lg hidden-md col-xs-12">
			<p><%= @sale.price%> € - <%= pluralize(@sale.bedroom, "Chambre") %></p>
		</div>
		<div class="col-md-2 hidden-xs  hidden-sm">
			<p class="bold">
				<%= @sale.price %> € 
			</p>
		</div>
	</div>
	<div class="mb-30"></div>
	<div class="row">
		<div class="col-md-4 col-xs-12 col-sm-4 col-lg-4">
			<% if @sale.photos.present? %>
				<div class="col-md-12">
					<!-- Carousel -->
      				<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        				<!-- Wrapper for slides -->
        				<div class="carousel-inner" role="listbox">
          					<div class="item active">
            					<%= cl_image_tag @sale.photos.first.path, width: 470, height: 350, :quality=>"auto:eco", crop: :fill %>
            					<div class="open-full-screen-carousel"></div>
          					</div>
          					<% @sale.photos[1...@sale.photos.size].each do |photo| %>
          	 					<div class="item">
          							<%= cl_image_tag photo.path, width: 470, height: 350, :quality=>"auto:eco", crop: :fill %>
          							<div class="open-full-screen-carousel"></div>
            					</div>
          					<% end %>
        				</div>
       					 <!-- Controls -->
        				<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
          					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          					<span class="sr-only">Previous</span>
        				</a>
        				<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
          					<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          					<span class="sr-only">Next</span>
        				</a>
					</div>
				</div>
			<% end %>
		</div>

		<div class="col-md-6 hidden-xs justify">
			<h4>Description</h4>
			<p style="text-align:justify"><%= @sale.description %></p>
		</div>
		<div class="col-xs-12 hidden-lg hidden-md hidden-sm">
			<h4 style="border:1px solid #999999; text-transform:uppercase; color:#006666; padding:10px;">Description</h4>
			<p style="text-align:justify"><%= @sale.description %></p>
		</div>
	</div>
	<% if @sale.seller_buyer.present? %>
		<div class="mt-30">
			<% if @sale.seller_buyer == "Commission Charge ACHETEUR" %>
						<p>Honoraires inclus dans le prix Charge Acheteur d'un montant de <%= @sale.fees %> €</p>
			<% else %>
						<p>Honoraires inclus dans le prix </p>
			<% end %>
		</div>
	<% end %>
	<div class="mb-50"></div>
	<div class="horizontal-line"></div>
	
	<div class="mb-50"></div>
	
	<%= render 'sales/shared/dpe' %>	

	<div class="mb-50"></div>
	<div class="horizontal-line"></div>
	
	<div class="mb-50"></div>
	
	<div class="row">
			
		
			
		
		<div class="col-md-6 hidden-xs">
			<h3>LES INFOS ESSENTIELLES</h3>
		</div>
		<div class="col-xs-12 hidden-lg hidden-md hidden-sm">
			<h4 style="border:1px solid #999999; text-transform:uppercase; color:#006666; padding:10px;">Les infos essentielles</h4>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<p>Prix: <%= @sale.price %>€</p>
			<p><%= pluralize(@sale.bedroom, "Chambre") %></p>
			<p>Taxe Foncière: <%= @sale.taxe %> €</p>
			<p>Chauffage: <%= @sale.heating %></p>
			<p>Exposition: <%= @sale.exposition %></p>
		</div>
		<div class="col-md-6 hidden-xs hidden-sm">
			<%= render 'sales/shared/conseiller' %>
		</div>
	</div>
	<div class="mb-50"></div>
</div>
<div class="container">
	<!-- <div class="row">
		<div class="col-md-12">
			<div id="map" class="mb-30 mt-30" style="width: 100%; height: 600px;"></div>
			<p>La géolocalisation est approximative</p>
		</div>
	</div>	 -->
	<div class="col-md-12">
		<div class="horizontal-line"></div>
	</div>
	
	<div class="col-xs-12 hidden-md hidden-lg hidden-sm text-center  ">
		<%= render 'sales/shared/conseiller' %>
	</div>
	
	<div class="col-sm-6 hidden-md hidden-lg hidden-xs  ">
		<%= render 'sales/shared/conseiller' %>
	</div>
</div>
	<div class="mb-50"></div>
</div>
<!-- <div class="container-fluid">
	<div class="row">
		<div class="photo-full-width" style="background-image: linear-gradient(135deg, rgba(150,109,105,0.2), rgba(150,109,105,0.4)), url('<%= cl_image_path @sale.photos.first.path %>');">
		</div>
	</div>
</div> -->

<% if current_user.try(:admin?) %>
	<%= simple_form_for [@sale, @link_partner] do |f| %>
	    <%= f.input :link %>
	    <%= f.association :partner %>
	    <%= f.submit %>
	<% end %>
<% end %>
<div class="container">
	<div class="row">
		<% if @sale.link_partners.count >=4 %>
			<div class="col-md-12 hidden-xs">
				<h3>NOS PRINCIPAUX PARTENAIRES</h3>
				<div class="mb-50"></div>
			</div>
			<% @sale.link_partners.each do |link_partner| %>
				<div class="col-md-3 hidden-xs">
			 		<!--<li><%= link_partner.partner.name%></li> -->
			 		<%= link_to "#{link_partner.link}" do  %>
			    		<%= cl_image_tag link_partner.partner.photo.path, width: 136, height: 67%>
					<% end %>
			 		<!-- <li><%= link_partner.link %></li> -->
			 		<div class="mb-50"></div>
			 	</div>
			<% end %>
		<% end %>

	</div>

</div>



<!-- FULL SCREEN CAROUSEL -->
<div id="full-screen-display" class="hidden">
	<div id="full-carousel-example-generic" class="carousel slide hidden" data-ride="carousel">
    <!-- Wrapper for slides -->
		<div class="carousel-inner" role="listbox">
			<div class="item active">
				<%= cl_image_tag @sale.photos.first.path, width: 800, height: 600, crop: :fill %>
			</div>
			<% @sale.photos[1...@sale.photos.size].each do |photo| %>
				<div class="item">
					<%= cl_image_tag photo.path, width: 800, height: 600, crop: :fill %>
				</div>
      		<% end %>
      	</div>



   
    	<!-- Controls -->
    	<a class="left carousel-control" href="#full-carousel-example-generic" role="button" data-slide="prev">
    		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      		<span class="sr-only">Previous</span>
    	</a>
    	<a class="right carousel-control" href="#full-carousel-example-generic" role="button" data-slide="next">
      		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      		<span class="sr-only">Next</span>
    	</a>
    	<div id="close-full-screen-carousel"><i class="fa fa-times" aria-hidden="true"></i></div>
  	</div>
</div>
<div id="full-wrapper-for-full-screen-carousel" class="hidden"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
		circle = [{lng: <%= @sale.longitude %>, lat: <%= @sale.latitude %>, radius: 200}]
     	circle_options = { strokeColor:"#FECC1F",strokeOpacity: 1, strokeWeight: 3, fillColor: 'transparent' }

      	var handler = Gmaps.build('Google');
      	handler.buildMap({ internal: { id: 'map' } }, function() {

      
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>